name: Enhanced Build and Push Docker Images

on:
  push:
    branches: [ master ] # Trigger on push to specific branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version as an environment variable
        run: echo "VERSION=2.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/AngularUI:${{ env.VERSION }} ./UI
          docker push ${{ secrets.DOCKER_USERNAME }}/AngularUI:${{ env.VERSION }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/DotNetAPI:${{ env.VERSION }} ./API
          docker push ${{ secrets.DOCKER_USERNAME }}/DotNetAPI:${{ env.VERSION }}